src/Entity/WithTimestamps.php
<?php

namespace App\Entity;

interface WithTimestamps
{
    public function getCreatedAt(): \DateTimeImmutable;

    public function getUpdatedAt(): \DateTimeImmutable;
}

templates/components/breadcrumb.html.twig
<ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="#">Examples</a></li>
    <li class="active">Blank page</li>
</ol>

templates/components/footer.html.twig
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Verze</b> 1.0.0
    </div>
    <strong>Copyright &copy; 2019 Jakub Vyvážil - vytvořeno jako ZP pro obor Aplikovaná informatika na <a href="https://www.vspj.cz" target="_blank" rel="nofollow noopener">VŠPJ</a>.</strong>
</footer>

templates/components/header.html.twig
<header class="main-header">
    <!-- Logo -->
    <a href="/" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini">
            <img src="{{ asset('build/img/logo-jibakurei-small.png') }}" alt="logo jibakurei" class="img-responsive" />
        </span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg">
            <img src="{{ asset('build/img/logo-horizontal-small.png') }}" alt="logo jibakurei" class="img-responsive" />
        </span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{ app.user.email|gravatar }}" class="user-image" alt="User Image">
                        <span class="hidden-xs">{{ app.user.email }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="{{ app.user.email|gravatar }}" class="img-circle" alt="User Image">

                            <p>
                                {{ app.user.email }}
                                <small>Registrován {{ app.user.createdAt|date('j. n. Y') }}</small>
                            </p>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            {#<div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">Profile</a>
                            </div>#}
                            <div class="pull-right">
                                <a href="{{ path('logout') }}" class="btn btn-default btn-flat">Odhlásit</a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

templates/components/sidebar.html.twig
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- sidebar menu: : style can be found in sidebar.less -->

        <div id="projects">
            <menu-projects></menu-projects>
        </div>

         <ul class="sidebar-menu" data-widget="tree">
            <li class="header">O PROJEKTU</li>
            <li><a href="https://bitbucket.org/jvyvazil/jibakurei/overview"><i class="fa fa-book"></i> <span>Zdrojový kód</span></a></li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

templates/components/title.html.twig
<h1>
    {{ title }}
    {% if subtitle %}
    <small>{{ subtitle }}</small>
    {% endif %}
</h1>